private _epitaphPool = [
  "I told you I was sick.",
  "I'll be back... as a ghost.",
  "I always knew this day would come.",
  "Rest in peace... finally.",
  "Gone but not forgotten... unfortunately.",
  "Here lies a legendary procrastinator.",
  "At least I lived a good life on Netflix.",
  "Sorry for the mess, I didn't have time to clean up.",
  "I finally caught up on my beauty sleep.",
  "I'm just taking a long nap... forever.",
  "Don't mourn for me, I'm off to haunt the living.",
  "I'd rather be alive, but here we are.",
  "Life was too short for this tombstone.",
  "I hope there's Wi-Fi in the afterlife.",
  "Died while attempting a TikTok challenge.",
  "Finally, some peace and quiet.",
  "Don't cry, I'm in a better place... probably.",
  "I guess I won't be needing that gym membership anymore.",
  "If you're reading this, you're standing too close.",
  "I asked for a pizza, not a tombstone!",
  "Remember me with laughter, not tears.",
  "Here lies the world's greatest nap-taker.",
  "I told you I wasn't feeling well.",
  "No more Mondays for me!",
  "I always wanted to be six feet under... said no one ever.",
  "Death by chocolate wasn't such a bad way to go.",
  "I'm just here for the ghost parties.",
  "I left all my belongings to the nearest thrift store.",
  "I promise I didn't mean to press the self-destruct button.",
  "Please don't water the flowers, they're artificial.",
  "Do ghosts have to pay taxes?",
  "I'll be watching you... from beyond the grave.",
  "I hope the afterlife has better Wi-Fi signal.",
  "Life's short, eat dessert first.",
  "In loving memory of my sanity.",
  "I regret nothing... well, maybe a few things.",
  "I always wanted to be part of a cemetery.",
  "I swear I didn't touch anything dangerous.",
  "Death is just the next great adventure.",
  "I hope they have pizza delivery in heaven.",
  "I left all my unfinished projects for you to complete.",
  "I died doing what I loved... eating junk food.",
  "I won't be needing these shoes anymore.",
  "Don't forget to feed my pet zombie.",
  "I apologize for any inconvenience my death may cause.",
  "I'll be the ghost in the corner at your future parties.",
  "Died while trying to figure out the meaning of life.",
  "I may be gone, but my legend lives on.",
  "I can't believe I'm saying this, but dying is exhausting.",
  "I'd appreciate it if you watered the plants on my grave.",
  "I'm haunting this place until they bring back disco.",
  "I hope the afterlife has better food options.",
  "Please don't bury me with my smartphone, it's haunted enough.",
  "I've finally achieved my dream of becoming a ghost.",
  "I'm just here for the eternal peace and quiet.",
  "I left a treasure map somewhere... good luck finding it.",
  "I hope heaven has an all-you-can-eat buffet.",
  "I'll be the poltergeist in your nightmares.",
  "I never thought I'd be popular after death.",
  "I'm just glad I don't have to pay bills anymore.",
  "I'm off to explore the great beyond.",
  "Please don't step on my grave, it's rude.",
  "I left my Netflix password in my will.",
  "I'm sorry for all the dad jokes... well, not really.",
  "I died as I lived... in complete chaos.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I always said I wanted to be buried with my collection of rubber ducks.",
  "I didn't mean to startle you, but I'm a ghost now.",
  "I hope my ghost can still enjoy pizza.",
  "I left my unfinished novel for you to complete. Good luck!",
  "I never thought I'd be caught dead in a cemetery.",
  "Death is just the beginning... of my nap time.",
  "I never met a ghost I didn't like.",
  "I finally have an excuse to wear pajamas all day.",
  "I'll be forever young in ghost years.",
  "I hope there's an endless supply of chocolate in the afterlife.",
  "Please don't forget to water the plants on my grave.",
  "I'm just here for the eternal peace and quiet.",
  "I left my favorite mug to haunt the office kitchen.",
  "I always said I wanted to be buried with my beloved pet rock.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I promise I didn't mean to become a ghost.",
  "Please don't disturb my eternal slumber.",
  "I left my unfinished jigsaw puzzle for you to solve.",
  "I never thought I'd have so much free time... as a ghost.",
  "I hope they have coffee in the afterlife, or I'm haunting someone.",
  "I died doing what I loved... eating pizza.",
  "I'll be the ghost in the corner at your future parties.",
  "Please don't bury me with my smartphone, it's haunted enough.",
  "I'm haunting this place until they bring back disco.",
  "I left a treasure map somewhere... good luck finding it.",
  "I hope heaven has an all-you-can-eat buffet.",
  "I'll be the poltergeist in your nightmares.",
  "I never thought I'd be popular after death.",
  "I'm just glad I don't have to pay bills anymore.",
  "I'm off to explore the great beyond.",
  "Please don't step on my grave, it's rude.",
  "I left my Netflix password in my will.",
  "I'm sorry for all the dad jokes... well, not really.",
  "I died as I lived... in complete chaos.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I always said I wanted to be buried with my collection of rubber ducks.",
  "I didn't mean to startle you, but I'm a ghost now.",
  "I hope my ghost can still enjoy pizza.",
  "I left my unfinished novel for you to complete. Good luck!",
  "I never thought I'd be caught dead in a cemetery.",
  "Death is just the beginning... of my nap time.",
  "I never met a ghost I didn't like.",
  "I finally have an excuse to wear pajamas all day.",
  "I'll be forever young in ghost years.",
  "I hope there's an endless supply of chocolate in the afterlife.",
  "Please don't forget to water the plants on my grave.",
  "I'm just here for the eternal peace and quiet.",
  "I left my favorite mug to haunt the office kitchen.",
  "I always said I wanted to be buried with my beloved pet rock.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I promise I didn't mean to become a ghost.",
  "Please don't disturb my eternal slumber.",
  "I left my unfinished jigsaw puzzle for you to solve.",
  "I never thought I'd have so much free time... as a ghost.",
  "I hope they have coffee in the afterlife, or I'm haunting someone.",
  "I died doing what I loved... eating pizza.",
  "I'll be the ghost in the corner at your future parties.",
  "Please don't bury me with my smartphone, it's haunted enough.",
  "I'm haunting this place until they bring back disco.",
  "I left a treasure map somewhere... good luck finding it.",
  "I hope heaven has an all-you-can-eat buffet.",
  "I'll be the poltergeist in your nightmares.",
  "I never thought I'd be popular after death.",
  "I'm just glad I don't have to pay bills anymore.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "Please don't forget to feed my pet ghost.",
  "I never thought I'd be this good at being dead.",
  "I'll be the life of the party... well, the afterlife of the party.",
  "I left my unfinished to-do list for you to ignore.",
  "I hope they serve pizza in heaven, or I'm haunting someone.",
  "I always said I wanted to be buried with my favorite pair of socks.",
  "Please don't forget to charge my ghostly devices.",
  "I'm just here for the ghostly gossip.",
  "I'm haunting this place until they bring back my favorite TV show.",
  "I hope heaven has a never-ending supply of ice cream.",
  "I'll be watching over you... and judging silently.",
  "Please don't forget to check for hidden treasures in my attic.",
  "I never thought I'd say this, but being dead is quite relaxing.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I'll be the ghostly prankster in your dreams.",
  "Please don't bury me with my secret recipe collection.",
  "I left my unfinished crossword puzzle for you to solve.",
  "I always said I wanted to be buried with my lucky socks.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I promise I didn't plan to become a ghost.",
  "Please don't wake me up, I'm enjoying my eternal slumber.",
  "I left my favorite ghostly mug to haunt the office kitchen.",
  "I always said I wanted to be buried with my beloved comic book collection.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I never thought I'd be caught dead in a cemetery... oh wait.",
  "Death is just the beginning... of my never-ending nap time.",
  "I never met a ghost I didn't like.",
  "I finally have an excuse to wear ghostly pajamas all day.",
  "I'll be forever young in ghost years.",
  "I hope there's an endless supply of ghostly chocolate in the afterlife.",
  "Please don't forget to water the ghostly plants on my grave.",
  "I'm just here for the eternal peace and quiet... and the ghost parties.",
  "I left my favorite ghostly mug to haunt the office kitchen.",
  "I always said I wanted to be buried with my beloved pet ghost.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I promise I didn't plan to become a ghost.",
  "Please don't wake me up, I'm enjoying my eternal slumber.",
  "I left my unfinished ghostly novel for you to complete. Good luck!",
  "I never thought I'd be caught dead in a cemetery... oh wait.",
  "Death is just the beginning... of my never-ending nap time.",
  "I never met a ghost I didn't like.",
  "I finally have an excuse to wear ghostly pajamas all day.",
  "I'll be forever young in ghost years.",
  "I hope there's an endless supply of ghostly chocolate in the afterlife.",
  "Please don't forget to water the ghostly plants on my grave.",
  "I'm just here for the eternal peace and quiet... and the ghost parties.",
  "I left my favorite ghostly mug to haunt the office kitchen.",
  "I always said I wanted to be buried with my beloved pet ghost.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I promise I didn't plan to become a ghost.",
  "Please don't wake me up, I'm enjoying my eternal slumber.",
  "I left my unfinished ghostly novel for you to complete. Good luck!",
  "I never thought I'd be caught dead in a cemetery... oh wait.",
  "Death is just the beginning... of my never-ending nap time.",
  "I never met a ghost I didn't like.",
  "I finally have an excuse to wear ghostly pajamas all day.",
  "I'll be forever young in ghost years.",
  "I hope there's an endless supply of ghostly chocolate in the afterlife.",
  "Please don't forget to water the ghostly plants on my grave.",
  "I'm just here for the eternal peace and quiet... and the ghost parties.",
  "I left my favorite ghostly mug to haunt the office kitchen.",
  "I always said I wanted to be buried with my beloved pet ghost.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I promise I didn't plan to become a ghost.",
  "Please don't wake me up, I'm enjoying my eternal slumber.",
  "I left my unfinished ghostly novel for you to complete. Good luck!",
  "I never thought I'd be caught dead in a cemetery... oh wait.",
  "Death is just the beginning... of my never-ending nap time.",
  "I never met a ghost I didn't like.",
  "I finally have an excuse to wear ghostly pajamas all day.",
  "I'll be forever young in ghost years.",
  "I hope there's an endless supply of ghostly chocolate in the afterlife.",
  "Please don't forget to water the ghostly plants on my grave.",
  "I'm just here for the eternal peace and quiet... and the ghost parties.",
  "I left my favorite ghostly mug to haunt the office kitchen.",
  "I always said I wanted to be buried with my beloved pet ghost.",
  "I hope they have Wi-Fi in the afterlife, or I'm haunting someone.",
  "I promise I didn't plan to become a ghost.",
  "Please don't wake me up, I'm enjoying my eternal slumber.",
  "I left my unfinished ghostly novel for you to complete. Good luck!",
  "I never thought I'd be caught dead in a cemetery... oh wait.",
  "Death is just the beginning... of my never-ending nap time.",
  "I never met a ghost I didn't like.",
  "I finally have an excuse to wear ghostly pajamas all day.",
  "I'll be forever young in ghost years."
];

private _epitaphs = [];

while { count _epitaphs < 900 } do { 

  _epitaphs pushBack (selectRandom _epitaphPool);

};

_epitaphs